### ISSUE TITLE
Alt and Caption Attributes

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [Ekito/ng2-cloudinary#1]
Is it possible with this library to assign values for attributes such as "alt" and "caption"?

**Comment by julienboulay** [comment]
Hi @wheredoesyourmindgo,
I've just added "alt" and "title" attributes to the cl-image component (version 0.5.1).
Caption can be added with standard HTML `<figure>` and `<figcaption>` tags as detailed [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure)
