### ISSUE TITLE
Signed uploads

### ISSUE THREAD

**Issue by avoliva** [Ekito/ng2-cloudinary#14]
Does this support signed cloudinary uploads?

**Comment by julienboulay** [comment]
Hi @avoliva, 

Signed uploads are not directly handled by this module, as it requires a backend to generate signature.
The idea to implement signed upload:

- use the file select to allow the user to select the file to upload
- override `onAfterAddingFile`on Uploader class to be able to request a signature to your backend (note that auto upload can not be used in this case)
- call `uploadItem` or `uploadAll` with the signature and payload to finally upload the file.

I will add an example soon.
