### ISSUE TITLE
Retrieving PNG image

### ISSUE THREAD

**Issue by adriendomoison** [Ekito/ng2-cloudinary#16]
Hi !

First of all, thank you for this amazing Cloudinary plugin !

I have a question: I need to use radius="max" on my pictures, so to remove the white backgroud, I need to use PNG images. How do you force the cl-image componant to read pictures as PNG ? It looks like even original PNG images are read as JPG, and I can't find anyway to change that. How can that be achieved ?

```
<cl-image [public-id]="profile.profilePicture" [cloud-name]="uploader.cloudName" width="100"
                        height="100" crop="fill" crop="thumb" radius="max" ></cl-image>
```

Thank you !

**Comment by julienboulay** [comment]
Hi @adriendomoison,

Thanks for your comments !

You can set the format by adding `format` attribute to the cl-image component like this :
```

**Comment by julienboulay** [comment]
You should also be aware that this component is deprecated as Cloudinary has released a [new Angular2 SDK](http://cloudinary.com/blog/new_angular_sdk_for_image_management_more_than_meets_the_eye)
This new SDK should fulfill all your requirements in terms of image transformations
