### ISSUE TITLE
Are all Cloudinary image attributes supported?

### ISSUE THREAD

**Issue by bjornharvold** [Ekito/ng2-cloudinary#2]
I am trying to get radius="max" to work but the url you generate is not catching it.

Cheers,
Bjorn

**Comment by julienboulay** [comment]
Hi @bjornharvold,

Some Cloudinary image attributes are not supported in version 0.5.
I'll try to implement it in the next days.
Also, please feel free to contribute to this project if you want.
Cheers

Julien

**Comment by julienboulay** [comment]
@bjornharvold : you should be able to use radius transformation with the latest component version (0.6.0)

**Comment by bjornharvold** [comment]
Great Julien! I will try it out. I sent your project to Cloudinary to let them know someone is doing some good work for Angular 2.

**Comment by julienboulay** [comment]
Hi @bjornharvold,
Many thanks for your contact with Cloudinary.
Please star this project as you like it ;)
