### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by ajonp** [Ekito/ng2-cloudinary#3]
@julienboulay 
How can you add key so that you don't have to use whitelist?

Otherwise I get 

> Upload preset must be whitelisted for unsigned uploads

**Comment by julienboulay** [comment]
Hi ajonp,

Only unsigned uploads are supported in this version.

Signed upload can not be supported for the moment:
Following this [article](https://support.cloudinary.com/hc/en-us/articles/203817991-How-to-generate-a-Cloudinary-signature-on-my-own-), you can generate the signature on the server side.
To add this signature, you should override `onBuildItemForm` in the CloudinaryUploader service, to request the signature on your server and add it to the FormData.
But `onBuildItemForm` is synchronous and then, you can not call your server asynchronously to request the signature before uploading.
I need to make a pullrequest to the ng2-file-upload project, for supporting asynchronous `onBuildItemForm` and other inherited functions...

**Comment by julienboulay** [comment]
@ajonp : I have added some example for direct image upload from the browser.

You can find it [here](https://ekito.github.io/ng2-cloudinary/demo/)
