### ISSUE TITLE
ng2-cloudinary has no exported member 'CloudinaryImageComponent'

### ISSUE THREAD

**Issue by tskytt** [Ekito/ng2-cloudinary#4]
Installing the latest version from npm (ng2-cloudinary@0.6.0) gives this error when importing:

import { CloudinaryImageComponent } from 'ng2-cloudinary';

I am running node 6.9.1.

Any idea why?

**Comment by julienboulay** [comment]
Hi tskytt,
You're right, `CloudinaryImageComponent` is not exported "as is" in the module package.
But if you import `Ng2CloudinaryModule`, you might not need to import `CloudinaryImageComponent`
I will fix the export in a future release.

If you really need the component, you can always import it like this :
`import { CloudinaryImageComponent } from 'ng2-cloudinary/src/cloudinary-image.component';`

**Comment by tskytt** [comment]
Hi julienboulay,

Thanks for your quick reply. That's great!
