### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by hakikihacioglu** [Ekito/ng2-cloudinary#5]
Hi,

I am using your package with Ionic 2 and ionic serve works as expected. When I try to build the app I get an error on ngc.

Error: Unexpected value 'Ng2CloudinaryModule' imported by the module 'AppModule'.
ngc failed

Do you have any ideas on that?

Thank you.

**Comment by julienboulay** [comment]
Hi,

It seems to be a known issue with Ionic2 and AOT compilation, when building an app for production.
See [this post](https://forum.ionicframework.com/t/unexpected-value-ng2completermodule-imported-by-the-module-appmodule/65922/13)

I may check if I can apply AOT compilation to Ng2CloudinaryModule bundle.

**Comment by bjornharvold** [comment]
+1 here. This module breaks with Angular CLI 1.0.0-beta.22-1. Big controversy about Angular team requiring all modules to support AOT going foward.

**Comment by julienboulay** [comment]
@hakikihacioglu, @bjornharvold I've deployed version 0.7.0 that solves this AOT compilation issue

**Comment by bjornharvold** [comment]
Awesome! Julien, thank you and happy holidays 💯
