### ISSUE TITLE
uploading image

### ISSUE THREAD

**Issue by finalight** [Ekito/ng2-cloudinary#6]
are there any demo or source code example in regards to actual image upload directly from browser? I couldn't find any relevant info for it

**Comment by julienboulay** [comment]
Hi @finalight,

There's no demo for the moment but there is a small code example in the README.md file.
I will update the documentation and demo soon.

Did you manage to implement direct upload from browser ?

Feel free to add relevant information and/or make a pull request if required

**Comment by finalight** [comment]
okay, managed to get it working

so this is how you would implement the function for the ability to upload

initialisation of the settings done below:
```
    private cloudinaryOptions: CloudinaryOptions = new CloudinaryOptions({
        cloud_name: 'asterzwx',
        upload_preset: 'e4mkj9rm',
        type: 'upload',
        autoUpload: false,
        queueLimit: 1,
        filters: [{
            queueLimit: 1
        }]
    });
```

the actual uploading code is here:

```
 this.uploader.addToQueue(this.filesToUpload);
            this.uploader.queue.splice(1, this.uploader.queue.length);
            this.uploader.uploadAll();
            let _self = this;
            this.uploader.onSuccessItem = (item: any, response: string, status: number, headers: any) => {
                _self.cloudinaryImage = JSON.parse(response);
                return { item, response, status, headers };
            };
```

the reason why I need to splice it by one element is because for some reason, the queue have 2 of the same item that are uploaded which I have no time to find out why. Even the queue limit at the option didnt work; thus the splice

**Comment by julienboulay** [comment]
@finalight I've updated your comment to obfuscate your cloud_name and upload_preset. You should keep it private to avoid hackers to upload a lot of images on your cloudinary account.

ng2FileSelect directive automatically add the file to the queue, so you don't need to call addToQueue in your code. This may be the cause of 2 files in queue...
Please have a look of the code sample on the [project home page](https://github.com/Ekito/ng2-cloudinary)

**Comment by finalight** [comment]
thanks, let me try and get back to you on that

**Comment by julienboulay** [comment]
The latest demo version gives an example of image upload directly from the browser
